namespace QIGN_MAIN
{
	public enum VISUAL_MODE
	{
		COMMON = 0,
		AUTODETECT = 1,
		NOSTILL = 2,
		HIGHCAM_SMT_AUTOSIZE = 3,
		HIGHCAM_SMT_AUTOSIZE_PRICISE_SECOND = 4,
		HIGHCAM_SMT_PRICISE_SECOND = 5,
		AUTODELTA_MARK = 6,
		CHESS_NONE_RESIZE = 7,
		CHESS_RESIZE = 8,
		LOOP_HALF_NOSTILL = 130,
		LOOP_HALF_HIGHCAM_SMT_AUTOSIZE = 131,
		LOOP_HALF_COMMON = 0x80,
		LOOP_CLOSE_HIGHCAM_SMT_AUTOSIZE = 131,
		LOOP_CLOSE_COMMON = 0x80,
		LOOP_HALF_AUTODETECT = 129,
		LOOP_HALF_HIGHCAM_SMT_AUTOSIZE_PRICISE_SECOND = 132,
		LOOP_HALF_HIGHCAM_SMT_PRICISE_SECOND = 133,
		LOOP_HALF_AUTODELTA_MARK = 134
	}
}
